/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ListsRouteImport } from './routes/lists'
import { Route as AddRouteImport } from './routes/add'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlaceIdRouteImport } from './routes/place.$id'

const ListsRoute = ListsRouteImport.update({
  id: '/lists',
  path: '/lists',
  getParentRoute: () => rootRouteImport,
} as any)
const AddRoute = AddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaceIdRoute = PlaceIdRouteImport.update({
  id: '/place/$id',
  path: '/place/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/lists': typeof ListsRoute
  '/place/$id': typeof PlaceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/lists': typeof ListsRoute
  '/place/$id': typeof PlaceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/lists': typeof ListsRoute
  '/place/$id': typeof PlaceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/add' | '/lists' | '/place/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/add' | '/lists' | '/place/$id'
  id: '__root__' | '/' | '/add' | '/lists' | '/place/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddRoute: typeof AddRoute
  ListsRoute: typeof ListsRoute
  PlaceIdRoute: typeof PlaceIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/lists': {
      id: '/lists'
      path: '/lists'
      fullPath: '/lists'
      preLoaderRoute: typeof ListsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add': {
      id: '/add'
      path: '/add'
      fullPath: '/add'
      preLoaderRoute: typeof AddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/place/$id': {
      id: '/place/$id'
      path: '/place/$id'
      fullPath: '/place/$id'
      preLoaderRoute: typeof PlaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddRoute: AddRoute,
  ListsRoute: ListsRoute,
  PlaceIdRoute: PlaceIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
